[browser]
gatherUsageStats = false

[server]
enableXsrfProtection = false
enableCORS = false
headless = true
maxUploadSize = 200
port = 8501
maxMessageSize = 200

[theme]
base = "light"
primaryColor = "#FF4B4B"

[client]
toolbarMode = "minimal" 
